import fs from 'node:fs';
import os from 'node:os';
import {fileURLToPath,pathToFileURL} from 'node:url';
import path from 'node:path';
const source=fileURLToPath(new URL('../public/',import.meta.url)),test=fs.mkdtempSync(os.tmpdir()+'/terminal-check-');
process.on('exit',()=>fs.rmSync(test,{recursive:true,force:true}));
fs.symlinkSync(source+'/vendor',test+'/vendor');
fs.writeFileSync(test+'/package.json','{"type":"module"}');
fs.cpSync(source+'/src',test+'/src',{recursive:true});if(!fs.existsSync(test+'/vendor'))fs.symlinkSync(source+'/vendor',test+'/vendor');
let core=fs.readFileSync(test+'/src/core.js','utf8');core=core.replace(/export const renderer=new T.WebGLRenderer[^\n]+/,"export const renderer={domElement:{addEventListener(){}},setSize(){}};");fs.writeFileSync(test+'/src/core.js',core);fs.writeFileSync(test+'/package.json','{"type":"module"}');
const els=new Map();globalThis.document={createElement(){return {width:512,height:128,getContext(){return new Proxy({},{get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>(o[k]=v,true)})}}},querySelector(id){if(!els.has(id))els.set(id,{textContent:'',style:{}});return els.get(id)}};globalThis.innerWidth=1440;globalThis.innerHeight=900;
const {T,C,world,scene}=await import(pathToFileURL(test+'/src/core.js').href);const {buildYard,containers}=await import(pathToFileURL(test+'/src/yard.js').href);const {Vehicle}=await import(pathToFileURL(test+'/src/vehicle.js').href);const {Cable}=await import(pathToFileURL(test+'/src/cable.js').href);const {Missions,validPlacement}=await import(pathToFileURL(test+'/src/missions.js').href);const {batchMeshes}=await import(pathToFileURL(test+'/src/optimize.js').href);
const items=buildYard();const staticYard=new T.Group();scene.add(staticYard);for(const o of [...scene.children])if(o!==staticYard&&(o.isMesh||o.isGroup)&&!containers.some(c=>c.body.mass>0&&c.mesh===o))staticYard.add(o);batchMeshes(staticYard);for(const o of containers)if(o.body.mass)batchMeshes(o.mesh);
const vehicle=new Vehicle();batchMeshes(vehicle.mesh,false);const events=[];const cable=new Cable(vehicle,(s,t)=>events.push({s,t}));const missions=new Missions(items,cable,vehicle,(s,t)=>events.push({s,t}));
function assert(cond,msg){if(!cond)throw Error(msg)}
const k=new Set();for(let i=0;i<120;i++){vehicle.update(1/60,k,false);cable.update(1/60,k);world.step(1/60)}assert(Math.abs(items.a.body.position.y-1.3)<.04,'Ground resting height');assert(Math.abs(items.c.body.position.y-2.9)<.05,'Truck resting height');assert(Math.abs(items.top.body.position.y-3.9)<.06,'Stack resting height');console.log('PASS: ground, truck, stacked container support; scene meshes',(()=>{let n=0;scene.traverse(o=>n+=!!o.isMesh);return n})());
// Position the anchor so a naturally settled magnet touches the target roof.
const tip=new T.Vector3(0,6.2,-8);cable.vehicle={tipPosition:()=>tip.clone()};cable.reset();cable.length=3.4;for(let i=0;i<240;i++){cable.update(1/60,k);world.step(1/60)}console.log('magnet',cable.magnet.position,'roof',items.a.body.position.y+1.3,'candidate',cable.candidate()?.id);assert(cable.candidate()===items.a,'Magnet candidate detection');const before=items.a.body.position.clone();cable.toggle();assert(items.a.body.position.distanceTo(before)<.00001,'Attach without teleport');assert(cable.attached===items.a,'Attach');for(let i=0;i<240;i++){tip.y+=.01;cable.update(1/60,k);world.step(1/60)}console.log('lift',items.a.body.position.y,'anchor',cable.anchor.position.y,'magnet',cable.magnet.position.y,'rope distance',cable.anchor.position.distanceTo(cable.magnet.position));assert(items.a.body.position.y>2.8,'Loaded lift');assert(cable.anchor.position.distanceTo(cable.magnet.position)<cable.length*1.2,'Rope stretch stability');
for(let i=0;i<90;i++){tip.x+=.035;cable.update(1/60,k);world.step(1/60)}const swing=Math.abs(cable.magnet.position.x-tip.x);assert(swing>.15,'Inertial swing');cable.release();const fallY=items.a.body.position.y;for(let i=0;i<360;i++){cable.update(1/60,k);world.step(1/60)}assert(items.a.body.position.y<fallY-1,'Released load falls');assert(Number.isFinite(items.a.body.position.x),'No NaN');console.log('PASS: proximity pickup, no teleport, lift, cable stretch, swing',swing.toFixed(2),'and release');
const o=items.b,t={x:31,z:-8,y:1.6,w:7.8,d:3.35};o.body.position.set(t.x,2.9,t.z);o.body.velocity.setZero();o.body.angularVelocity.setZero();o.body.quaternion.set(0,0,0,1);assert(validPlacement(o,t),'Truck valid');o.body.position.z+=.5;assert(!validPlacement(o,t),'Overhang rejected');o.body.position.set(t.x,4,t.z);assert(!validPlacement(o,t),'Passing above target rejected');o.body.position.y=2.9;o.body.velocity.x=1;assert(!validPlacement(o,t),'Moving load rejected');console.log('PASS: precise mission validation, height, overhang, velocity');
missions.reset();assert(cable.attached===null,'Reset releases joint');assert(vehicle.body.position.z===4,'Reset vehicle');console.log('PASS: mission reset');

// Exercise actual fixed-step drive and contact response against an immovable stack.
vehicle.body.position.set(-43,1.2,-24);vehicle.heading=0;vehicle.body.quaternion.set(0,0,0,1);for(let i=0;i<600;i++){vehicle.update(1/60,new Set(['KeyW']),false);world.step(1/60)}assert(vehicle.body.position.z>-33,'Vehicle cannot drive through static container stack');console.log('PASS: acceleration and vehicle collision',vehicle.body.position.z.toFixed(2));
missions.reset();for(let expected=0;expected<5;expected++){assert(missions.index===expected,'Expected mission '+expected);for(const j of missions.mission.jobs){j.o.body.position.set(j.t.x,j.t.y+j.o.h/2,j.t.z);j.o.body.quaternion.set(0,0,0,1);j.o.body.velocity.setZero();j.o.body.angularVelocity.setZero();}for(let i=0;i<300;i++){world.step(1/60);missions.update(1/60,i/60)}}assert(missions.completed===1,'All five missions complete');console.log('PASS: all five missions, actual support contacts, automatic advance and new shift');
// Regression: exercise the real arm, including its world-space rotation and mesh batching.
missions.resetAll();cable.vehicle=vehicle;vehicle.reset();cable.reset();
assert(vehicle.tipPosition().y>4.2*vehicle.size,'Initial boom tip must be above the cab, not underground');assert(cable.magnet.position.y>2.5,'Initial magnet must be visible above the ground');
let tip0=vehicle.tipPosition();vehicle.update(.25,new Set(['ArrowUp']),false);assert(vehicle.tipPosition().y>tip0.y,'ArrowUp raises the real tip');tip0=vehicle.tipPosition();vehicle.update(.25,new Set(['KeyX']),false);assert(vehicle.tipPosition().distanceTo(vehicle.body.position)>tip0.distanceTo(vehicle.body.position),'Extension increases reach');
for(const wheel of vehicle.wheels)batchMeshes(wheel.rolling);vehicle.body.position.z-=1;vehicle.steer=.7;vehicle.draw();assert(vehicle.wheels.every(w=>Math.abs(w.rolling.rotation.x)>1),'Every wheel rolls after batching');assert(vehicle.wheels.filter(w=>w.front).every(w=>w.steering.rotation.y>.2),'Front wheels steer');assert(vehicle.wheels.every(w=>w.rolling.children.length>0),'Wheel geometry remains under animated pivot');
for(const o of containers.filter(c=>c.body.mass===0)){const bottom=o.body.position.y-o.h/2;assert(bottom<.02||containers.some(b=>b!==o&&Math.abs(b.body.position.x-o.body.position.x)<.1&&Math.abs(b.body.position.z-o.body.position.z)<.1&&Math.abs(b.body.position.y+b.h/2-bottom)<.02),'No unsupported decorative container '+o.id)}
missions.resetAll();vehicle.lift=.61;vehicle.body.position.set(-.15*vehicle.size,1.2*vehicle.size,-8+(Math.cos(.61)*9.5-.35)*vehicle.size);vehicle.updateArm();vehicle.draw();vehicle.mesh.updateMatrixWorld(true);cable.reset();for(let i=0;i<240;i++){vehicle.update(1/60,new Set(),false);cable.update(1/60,new Set());world.step(1/60)}assert(cable.candidate()===items.a,'Real arm positions magnet on target roof');cable.toggle();for(let i=0;i<240;i++){vehicle.update(1/60,new Set(['ArrowUp']),true);cable.update(1/60,new Set());world.step(1/60)}assert(items.a.body.position.y>3,'Real arm raises connected load');assert(cable.magnet.position.y>4,'Magnet remains above ground with load');console.log('PASS: actual boom orientation, telescoping, visible magnet, animated wheels, supported decoration and real-arm pickup/lift');
// Regression: operator pauses after attaching before lifting.
missions.resetAll();cable.vehicle=vehicle;vehicle.lift=.61;vehicle.body.position.set(-.15*vehicle.size,1.2*vehicle.size,-8+(Math.cos(.61)*9.5-.35)*vehicle.size);vehicle.updateArm();vehicle.draw();vehicle.mesh.updateMatrixWorld(true);cable.reset();
const step=(keys=new Set())=>{vehicle.update(1/60,keys,!!cable.attached);cable.update(1/60,keys);world.step(1/60)};
for(let i=0;i<600;i++)step();assert(cable.candidate()===items.a,'Rested pickup target');cable.toggle();for(let i=0;i<600;i++)step();console.log('Before delayed lift: sleep state',items.a.body.sleepState);for(let i=0;i<300;i++)step(new Set(['ArrowUp']));console.log('After delayed lift: height',items.a.body.position.y,'rope',cable.anchor.position.distanceTo(cable.magnet.position));assert(items.a.body.position.y>3,'Load must rise after waiting attached on ground');assert(cable.anchor.position.distanceTo(cable.magnet.position)<cable.length*1.15,'Loaded cable must not stretch after waiting');
const raised=items.a.body.position.y;for(let i=0;i<600;i++)step();assert(items.a.body.position.y>raised-.2,'Suspended load stays awake while parked');for(let i=0;i<60;i++)step(new Set(['KeyE']));for(let i=0;i<180;i++)step();assert(items.a.body.position.y>raised+.8,'Winch raises load');assert(cable.anchor.position.distanceTo(cable.magnet.position)<cable.length+.03,'Tension limiter tracks winch length');cable.release(false);assert(items.a.body.allowSleep===true,'Release restores sleeping optimization');for(let i=0;i<900;i++)step();assert(items.a.body.position.y<1.4,'Released load returns to ground');console.log('PASS: parked suspension, winch, bounded cable length, release and restored sleep');
// Horizontal rotation of a suspended magnetic load without teleporting its pose.
missions.resetAll();cable.vehicle=vehicle;vehicle.lift=.61;vehicle.body.position.set(-.15*vehicle.size,1.2*vehicle.size,-8+(Math.cos(.61)*9.5-.35)*vehicle.size);vehicle.updateArm();vehicle.draw();vehicle.mesh.updateMatrixWorld(true);vehicle.armColliders.sync(0);cable.reset();for(let i=0;i<240;i++)step();cable.toggle();for(let i=0;i<180;i++)step(new Set(['ArrowUp','KeyX']));
for(let i=0;i<240;i++)step();
for(let i=0;i<35;i++)step(new Set(['KeyQ']));for(let i=0;i<240;i++)step();
const axisBefore=items.a.body.quaternion.vmult(new C.Vec3(1,0,0));for(let i=0;i<300;i++)step(new Set(['KeyJ']));const axisAfter=items.a.body.quaternion.vmult(new C.Vec3(1,0,0));assert(axisBefore.dot(axisAfter)<.4,'J rotates the actual magnetic cargo horizontally');for(let i=0;i<240;i++)step();assert(Math.abs(items.a.body.angularVelocity.y)<.1,'Yaw brakes after releasing J');assert(cable.anchor.position.distanceTo(cable.magnet.position)<cable.length+.05,'Rotation preserves cable length');cable.release(false);console.log('PASS: torque-driven magnetic yaw, braking, maintained cable length');
// Second vehicle: hydraulic spreader acquires, raises, turns and releases the same mission load.
const {Grapple}=await import(pathToFileURL(test+'/src/grapple.js').href);missions.resetAll();vehicle.body.position.set(-10,1.2,38);vehicle.draw();vehicle.mesh.updateMatrixWorld(true);vehicle.armColliders.sync(0);cable.reset();
const stacker=new Vehicle({model:'grapple',spawn:[14,1.2,36]});const grapple=new Grapple(stacker,()=>{});stacker.lift=.336;stacker.body.position.set(-.15*stacker.size,1.2*stacker.size,-8+(Math.cos(.336)*9.5-.35)*stacker.size+2);stacker.updateArm();stacker.draw();stacker.mesh.updateMatrixWorld(true);stacker.armColliders.sync(0);grapple.reset();
const stepG=(keys=new Set())=>{stacker.update(1/60,keys,!!grapple.attached);grapple.update(1/60,keys);world.step(1/60);stacker.draw();grapple.draw()};for(let i=0;i<240;i++)stepG();assert(grapple.candidate()===items.a,'Grapple reaches container roof');const pickupPosition=items.a.body.position.clone();grapple.toggle();assert(items.a.body.position.distanceTo(pickupPosition)<1e-8,'Grapple connects without teleporting');for(let i=0;i<600;i++)stepG();assert(items.a.body.sleepState===C.Body.AWAKE,'Grapple load stays awake');for(let i=0;i<180;i++)stepG(new Set(['ArrowUp']));assert(items.a.body.position.y>5,'Hydraulic arm raises container');let beforeAxis=items.a.body.quaternion.vmult(new C.Vec3(1,0,0));for(let i=0;i<180;i++)stepG(new Set(['KeyL']));for(let i=0;i<240;i++)stepG();let afterAxis=items.a.body.quaternion.vmult(new C.Vec3(1,0,0));assert(beforeAxis.dot(afterAxis)<.35,'Grapple motor rotates load');grapple.release(false);assert(items.a.body.allowSleep,'Grapple release restores sleep');for(let i=0;i<360;i++)stepG();assert(items.a.body.position.y<1.4,'Grapple released cargo falls');console.log('PASS: second vehicle proximity pickup, physical lift, yaw and release');
// Resolve an actual contact between a moving cargo and the solid boom.
const {bodyBox}=await import(pathToFileURL(test+'/src/core.js').href);const part=stacker.armColliders.parts[0];const impact=bodyBox(.6,.6,.6,part.body.position.x+1.3,part.body.position.y,part.body.position.z,100);impact.allowSleep=false;impact.velocity.set(-2,0,0);let boomContacts=0;impact.addEventListener('collide',e=>{if(stacker.armColliders.parts.some(p=>p.body===e.body))boomContacts++});for(let i=0;i<90;i++)stepG();assert(boomContacts>0,'Cargo collides with articulated boom');world.removeBody(impact);console.log('PASS: actual rigid-body boom contact');
stacker.reset();grapple.reset();for(let i=0;i<180;i++)stepG(new Set(['KeyW']));assert(stacker.speed>7.5,'Unloaded speed increased');console.log('PASS: increased speed', (stacker.speed*3.6).toFixed(1),'km/h');
